model_id: DTI/DrugBAN
model_type: drugban
name: drugban
task: dti
objective: discriminative
auto_map:
  AutoProteinConfig: configuration.DrugBANConfig
  AutoProteinModel: modeling.DrugBANModel
pretrained:
  local_dir: weights
  filename: drugban.pt
  url: ""
streams:
  drug:
    modality: molecule
    input_key: smiles
    processor: rdkit_graph
    processor_kwargs:
      max_nodes: 290
  target:
    modality: sequence
    input_key: sequence
    processor: amino_acid
    processor_kwargs:
      max_length: 1000
components:
  embedders:
    drug:
      id: molecule/gcn
      kwargs:
        in_feats: 75
        embedding_dim: 128
        hidden_dim: 128
        layers: 3
    target:
      id: sequence/cnn
      kwargs:
        vocab_size: 26
        embedding_dim: 128
        filter_dim: 128
        kernels:
          - 3
          - 6
          - 9
  predictor:
    id: dti/ban
    kwargs:
      molecule_dim: 128
      protein_dim: 128
      hidden_dim: 256
      heads: 2
      k: 3
      dropout: 0.2
      decoder_hidden_dim: 512
      decoder_output_dim: 128
      binary_dim: 1
training:
  batch_size: 64
  epochs: 100
  learning_rate: 0.00005
loss:
  type: binary_cross_entropy
evaluation:
  metrics:
    - auroc
    - auprc
    - accuracy
    - f1
    - threshold
interpretation:
  method: bilinear_attention_map
